/*!40101 SET character_set_client = latin1 */;
/*!40103 SET TIME_ZONE='+00:00' */;

--
-- Dump dei dati per la tabella meeting_programs staffette
-- 
INSERT INTO meeting_programs (event_order,user_id,meeting_event_id,gender_type_id,category_type_id,pool_type_id,lock_version,created_at,updated_at) VALUES 
(5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15101 and et.code = 'S4X50MX'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '001-119' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15101 and et.code = 'S4X50MX'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '001-119' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15101 and et.code = 'S4X50MX'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '120-159' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15101 and et.code = 'S4X50MX'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '120-159' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15101 and et.code = 'S4X50MX'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '160-999' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(5,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15101 and et.code = 'S4X50MX'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '160-999' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE());

--
-- Dump dei dati per la tabella meeting_relay_results
-- 
INSERT INTO meeting_relay_results (rank,meeting_points,minutes,seconds,hundreds,user_id,team_id,is_disqualified,is_out_of_race,meeting_program_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(1,'24',2,16,0,2,10,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15101),0,CURDATE(),CURDATE()),
(2,'21',2,28,30,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(3,'0',2,31,20,2,10,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15101),0,CURDATE(),CURDATE()),
(3,'18',2,31,20,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15101),0,CURDATE(),CURDATE()),
(5,'0',2,39,40,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15101),0,CURDATE(),CURDATE()),
(6,'9',2,39,90,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15101),0,CURDATE(),CURDATE()),
(7,'0',2,40,20,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(8,'3',2,44,40,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15101),0,CURDATE(),CURDATE()),
(9,'2',2,46,30,2,21,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 21 and m.id = 15101),0,CURDATE(),CURDATE()),
(1,'24',1,57,80,2,21,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 21 and m.id = 15101),0,CURDATE(),CURDATE()),
(2,'21',2,0,20,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(3,'18',2,4,10,2,32,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 32 and m.id = 15101),0,CURDATE(),CURDATE()),
(4,'0',2,14,30,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(5,'12',2,15,80,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15101),0,CURDATE(),CURDATE()),
(6,'9',2,24,10,2,10,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15101),0,CURDATE(),CURDATE()),
(7,'6',2,24,60,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15101),0,CURDATE(),CURDATE()),
(8,'3',2,25,70,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15101),0,CURDATE(),CURDATE()),
(1,'24',2,31,30,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15101),0,CURDATE(),CURDATE()),
(2,'21',2,38,60,2,11,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15101),0,CURDATE(),CURDATE()),
(3,'18',2,54,10,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15101),0,CURDATE(),CURDATE()),
(4,'15',2,55,80,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(5,'12',3,20,10,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15101),0,CURDATE(),CURDATE()),
(1,'24',2,0,0,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15101),0,CURDATE(),CURDATE()),
(2,'21',2,2,40,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15101),0,CURDATE(),CURDATE()),
(3,'18',2,2,70,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(4,'15',2,5,20,2,10,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15101),0,CURDATE(),CURDATE()),
(5,'12',2,6,90,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15101),0,CURDATE(),CURDATE()),
(6,'9',2,10,40,2,9,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15101),0,CURDATE(),CURDATE()),
(7,'0',2,18,70,2,10,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15101),0,CURDATE(),CURDATE()),
(8,'3',2,21,0,2,4,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 4 and m.id = 15101),0,CURDATE(),CURDATE()),
(9,'0',2,32,80,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(10,'0',2,33,80,2,4,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 4 and m.id = 15101),0,CURDATE(),CURDATE()),
(11,'0',3,1,10,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15101),0,CURDATE(),CURDATE()),
(12,'0',3,10,50,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(1,'24',2,52,90,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(2,'21',2,38,90,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15101),0,CURDATE(),CURDATE()),
(3,'18',2,34,20,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15101),0,CURDATE(),CURDATE()),
(4,'15',2,31,50,2,10,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'F' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15101),0,CURDATE(),CURDATE()),
(1,'24',2,7,30,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(2,'21',2,10,40,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15101),0,CURDATE(),CURDATE()),
(3,'18',2,17,0,2,32,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 32 and m.id = 15101),0,CURDATE(),CURDATE()),
(4,'15',2,17,90,2,4,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 4 and m.id = 15101),0,CURDATE(),CURDATE()),
(5,'12',2,18,80,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15101),0,CURDATE(),CURDATE()),
(6,'0',2,22,0,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15101),0,CURDATE(),CURDATE()),
(7,'0',2,29,20,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15101),0,CURDATE(),CURDATE()),
(8,'3',2,32,20,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15101),0,CURDATE(),CURDATE()),
(9,'0',2,40,40,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15101),0,CURDATE(),CURDATE()),
(10,'0',2,45,10,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15101),0,CURDATE(),CURDATE()),
(11,'2',2,46,10,2,11,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15101),0,CURDATE(),CURDATE()),
(0,'0',0,0,0,2,9,1,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15101 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15101),0,CURDATE(),CURDATE());

commit;