-- Leega
-- 19/04/2016
-- Fix Cavallo relay

DELETE FROM meeting_relay_swimmers where id between 201 and 204;

--
-- Aggiunta dati staffette meeting 15105
-- 
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,minutes,seconds,hundreds,user_id,reaction_time,meeting_relay_result_id,badge_id,stroke_type_id,lock_version,created_at,updated_at) VALUES 
(201,1,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'SERRAIUOLO MARCO' and b.team_id = 1 and b.season_id = 151),0,27,17,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50SL' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '120-159' and mrr.relay_header = '' and mrr.rank = 3),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15105) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'VALCAVI LUCA' and b.team_id = 1 and b.season_id = 151)),(select t.id from stroke_types t where t.code = 'SL'),0,CURDATE(),CURDATE()),
(202,2,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'RONZONI ALESSANDRO' and b.team_id = 1 and b.season_id = 151),0,30,25,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50SL' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '120-159' and mrr.relay_header = '' and mrr.rank = 3),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15105) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'RONZONI ALESSANDRO' and b.team_id = 1 and b.season_id = 151)),(select t.id from stroke_types t where t.code = 'SL'),0,CURDATE(),CURDATE()),
(203,3,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'VALCAVI LUCA' and b.team_id = 1 and b.season_id = 151),0,27,94,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50SL' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '120-159' and mrr.relay_header = '' and mrr.rank = 3),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15105) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'SERRAIUOLO MARCO' and b.team_id = 1 and b.season_id = 151)),(select t.id from stroke_types t where t.code = 'SL'),0,CURDATE(),CURDATE()),
(204,4,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FOSSILE ROBERTO' and b.team_id = 1 and b.season_id = 151),0,29,94,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50SL' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '120-159' and mrr.relay_header = '' and mrr.rank = 3),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15105) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'FOSSILE ROBERTO' and b.team_id = 1 and b.season_id = 151)),(select t.id from stroke_types t where t.code = 'SL'),0,CURDATE(),CURDATE());
