-- Leega
-- 03/02/2016
-- CSI time standards for 50Special ranking calculation

--
-- Dump dei dati per la tabella time_standards
-- 
INSERT INTO time_standards (minutes,seconds,hundreds,season_id,gender_type_id,category_type_id,event_type_id,pool_type_id,lock_version,created_at,updated_at) VALUES 
(0,31,86,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '50FA'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(1,17,76,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100FA'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(0,35,58,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '50DO'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(1,19,46,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100DO'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(0,38,34,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '50RA'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(1,25,10,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100RA'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(0,29,52,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '50SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(1,6,14,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(2,28,78,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '200SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(5,22,6,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '400SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(11,58,38,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '800SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(1,14,44,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100MI'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(2,48,90,151,(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '200MI'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(0,27,60,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '50FA'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(1,2,72,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100FA'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(0,29,54,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '50DO'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(1,6,40,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100DO'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(0,33,26,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '50RA'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(1,16,66,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100RA'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(0,25,80,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '50SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(0,56,2,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(2,9,20,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '200SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(4,38,40,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '400SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(10,5,0,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '800SL'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(1,3,74,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '100MI'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(2,27,46,151,(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 151),(select t.id from event_types t where t.code = '200MI'),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE());

commit;