--
-- PassagesBatchUpdater: recorded from actions by [User: leega (Marco Ligabue) ID: 2]
-- 03 May 2016 16:30:30
-- Begin script
--

INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5215, 0, 32, 76, 53377, 2, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 32, 76, 0, 339315, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5216, 0, 39, 62, 53377, 4, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 12, 38, 0, 339315, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5217, 0, 41, 62, 53377, 6, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 54, 0, 0, 339315, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5218, 0, 45, 9, 53377, 8, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 39, 9, 0, 339315, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5219, 0, 43, 0, 53392, 2, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 43, 0, 0, 339348, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5220, 0, 50, 23, 53392, 4, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 33, 23, 0, 339348, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5221, 0, 47, 92, 53392, 6, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 21, 15, 0, 339348, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5222, 0, 53, 19, 53392, 8, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 14, 34, 0, 339348, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5223, 0, 39, 36, 53398, 2, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 39, 36, 0, 339373, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5224, 0, 46, 26, 53398, 4, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 25, 62, 0, 339373, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5225, 0, 47, 52, 53398, 6, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 13, 14, 0, 339373, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5226, 0, 46, 59, 53398, 8, 2, '2016-05-03 14:30:30', '2016-05-03 14:30:30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 59, 73, 0, 339373, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5227, 0, 39, 91, 53409, 2, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 39, 91, 0, 339411, NULL, 1463, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5228, 0, 45, 16, 53409, 4, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 25, 7, 0, 339411, NULL, 1463, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5229, 0, 45, 83, 53409, 6, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 10, 90, 0, 339411, NULL, 1463, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5230, 0, 45, 53, 53409, 8, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 56, 43, 0, 339411, NULL, 1463, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5231, 0, 40, 88, 53328, 2, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 40, 88, 0, 339085, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5232, 0, 44, 86, 53328, 4, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 25, 74, 0, 339085, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5233, 0, 37, 75, 53333, 2, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 37, 75, 0, 339105, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5234, 0, 42, 97, 53333, 4, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 20, 72, 0, 339105, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5235, 0, 31, 32, 53346, 2, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 31, 32, 0, 339180, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5236, 0, 35, 61, 53346, 4, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 6, 93, 0, 339180, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5237, 0, 29, 90, 53342, 2, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 29, 90, 0, 339144, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5238, 0, 34, 67, 53342, 4, 2, '2016-05-03 14:30:31', '2016-05-03 14:30:31', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 4, 57, 0, 339144, NULL, 1025, 1);
