/*!40101 SET character_set_client = latin1 */;
/*!40103 SET TIME_ZONE='+00:00' */;

-- Fix meeting program
update meeting_events set event_type_id = 32 where id = 3876;

--
-- Dump dei dati per la tabella meeting_programs staffette
-- 
INSERT INTO meeting_programs (event_order,user_id,meeting_event_id,gender_type_id,category_type_id,pool_type_id,lock_version,created_at,updated_at) VALUES 
(1,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15103 and et.code = 'M4X50SL'),(select t.id from gender_types t where t.code = 'X'),(select t.id from category_types t where t.code = '001-119' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(2,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15103 and et.code = 'M4X50SL'),(select t.id from gender_types t where t.code = 'X'),(select t.id from category_types t where t.code = '120-159' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(3,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15103 and et.code = 'M4X50SL'),(select t.id from gender_types t where t.code = 'X'),(select t.id from category_types t where t.code = '160-999' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE());

--
-- Dump dei dati per la tabella meeting_relay_results
-- 
INSERT INTO meeting_relay_results (rank,meeting_points,minutes,seconds,hundreds,user_id,team_id,is_disqualified,is_out_of_race,meeting_program_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(1,'24',1,53,20,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(2,'21',1,56,80,2,11,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15103),0,CURDATE(),CURDATE()),
(3,'18',1,58,70,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15103),0,CURDATE(),CURDATE()),
(4,'15',2,2,20,2,21,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 21 and m.id = 15103),0,CURDATE(),CURDATE()),
(5,'0',2,2,60,2,21,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 21 and m.id = 15103),0,CURDATE(),CURDATE()),
(6,'0',2,3,70,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(7,'0',2,7,90,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(8,'0',2,13,10,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(1,'24',1,56,10,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(2,'0',2,2,20,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(3,'18',2,2,60,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15103),0,CURDATE(),CURDATE()),
(4,'0',2,9,20,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(5,'12',2,12,80,2,4,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 4 and m.id = 15103),0,CURDATE(),CURDATE()),
(6,'0',2,14,40,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(7,'6',2,18,90,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15103),0,CURDATE(),CURDATE()),
(1,'24',1,57,30,2,9,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15103),0,CURDATE(),CURDATE()),
(2,'21',2,9,80,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15103),0,CURDATE(),CURDATE()),
(3,'18',2,14,90,2,11,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15103),0,CURDATE(),CURDATE()),
(4,'15',2,17,10,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(5,'0',2,19,70,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15103),0,CURDATE(),CURDATE()),
(6,'0',2,22,10,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15103),0,CURDATE(),CURDATE()),
(7,'0',2,30,60,2,11,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50SL' and ms.meeting_id = 15103 and gt.code = 'X' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15103),0,CURDATE(),CURDATE());

commit;