-- Leega
-- 27/05/2016
-- Meeting programs adj

--
-- Aggiunta dati FIN 15/16 per la tabella meeting_sessions
-- 
INSERT INTO meeting_sessions (id,session_order,scheduled_date,meeting_id,swimming_pool_id,warm_up_time,begin_time,notes,description,user_id,day_part_type_id,lock_version,created_at,updated_at) VALUES 
(1273,4,'2016-05-22',15333,135,'15:00:00','15:30:00','','FINALI',2,(select t.id from day_part_types t where t.code = 'P'),0,CURDATE(),CURDATE());

--
-- Aggiornamento orari sessioni per il meeting 15333
-- 
update meeting_sessions set warm_up_time = '7:45:00', begin_time = '8:30:00', scheduled_date = '2016-05-21' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 1) a);
update meeting_sessions set warm_up_time = '14:30:00', begin_time = '15:00:00', scheduled_date = '2016-05-21' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 2) a);
update meeting_sessions set warm_up_time = '8:30:00', begin_time = '9:00:00', scheduled_date = '2016-05-22' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 3) a);
update meeting_sessions set warm_up_time = '15:00:00', begin_time = '15:30:00', scheduled_date = '2016-05-22' where id > 0 and id = (select a.id from (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 4) a);

--
-- Aggiornamento programma gare per il meeting 15333
-- 
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 1), event_type_id = (select et.id from event_types et where et.code = '1500SL') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 1) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 1), event_type_id = (select et.id from event_types et where et.code = '200DO') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 2) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 1), event_type_id = (select et.id from event_types et where et.code = 'M4X100MI') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 3) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 2), event_type_id = (select et.id from event_types et where et.code = '200MI') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 4) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 2), event_type_id = (select et.id from event_types et where et.code = '200SL') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 5) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 2), event_type_id = (select et.id from event_types et where et.code = '800SL') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 6) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 2), event_type_id = (select et.id from event_types et where et.code = 'S4X100SL') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 7) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 3), event_type_id = (select et.id from event_types et where et.code = '100DO') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 8) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 3), event_type_id = (select et.id from event_types et where et.code = '50FA') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 9) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 3), event_type_id = (select et.id from event_types et where et.code = '100SL') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 10) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 3), event_type_id = (select et.id from event_types et where et.code = '50RA') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 11) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 3), event_type_id = (select et.id from event_types et where et.code = 'M4X50MI') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 12) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 4), event_type_id = (select et.id from event_types et where et.code = '50SL') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 13) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 4), event_type_id = (select et.id from event_types et where et.code = '100MI') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 14) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 4), event_type_id = (select et.id from event_types et where et.code = '50DO') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 15) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 4), event_type_id = (select et.id from event_types et where et.code = '100RA') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 16) a);
update meeting_events set meeting_session_id = (select id from meeting_sessions ms where ms.meeting_id = 15333 and ms.session_order = 4), event_type_id = (select et.id from event_types et where et.code = 'S4X50SL') where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 17) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 18) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 19) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 20) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 21) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 22) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 23) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 24) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 25) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 26) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 27) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 28) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 29) a);
delete from meeting_events where id > 0 and id = (select a.id from (select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id where ms.meeting_id = 15333 and me.event_order = 30) a);
