FORMAT: 1A
HOST: http://master-goggles.org

# Goggles API
Goggles API involves miscellaneous server-side actions for score and statistics computation
of [http://steveoro.github.io/goggles]. Some of the actions may require authentication.

# Goggles Front-End

## User-Training list or single row [/user_trainings/json_list{/id}{&limit}{&query}]
### Retrieve User-Training details or list all available User-Training [GET]
Retrieves User Training data.
Currently this resource works only via (XHR) AJAX request, behind user authentication.
Future versions will introduce OAuth/Facebook/Google+ user authorization.

+ Parameters
    - id(optional)
        Filter bypass, used to retrieve the row instance having the specified id. When present, all other parameters are ignored.
    - limit(optional)
        Used to limit the array of results; the default top limit is set to 1000 for performance reasons (but it can be overridden by this parameter).
    - query(optional)
        A string match for the verbose description; when equal to '%', the parameter is ignored.

+ Response 200 (application/json)

        [{
         "label": "localized short description of the exercise",
         "value": row.id,
         "tot_distance": row.compute_total_distance(),
         "tot_secs": row.compute_total_seconds()
         "user_name": row.get_user_name(),
         "swimmer_level_type_description": row.get_swimmer_level_type( :i18n_description ),
         "swimmer_level_type_alternate": row.get_swimmer_level_type( :i18n_alternate )
        }, {
         ...
        }]


## Exercise list or single row [/exercises/json_list{/id}{?training_step_type_id}{&limit}{&query}]
### Retrieve exercise details or list exercises based on "training step type" [GET]
Retrieves Exercise data.
Currently this resource works only via (XHR) AJAX request, behind user authentication.
Future versions will introduce OAuth/Facebook/Google+ user authorization.

+ Parameters
    - id(optional)
        Filter bypass, used to retrieve the row instance having the specified id. When present, all other parameters are ignored.
    - training_step_type_id(optional)
        When present, it is used as a filtering parameter for the result data set.
    - limit(optional)
        Used to limit the array of results; the default top limit is set to 1000 for performance reasons (but it can be overridden by this parameter).
    - query(optional)
        A string match for the verbose description; when equal to '%', the parameter is ignored.

+ Response 200 (application/json)

        [{
         "label": "localized short description of the exercise",
         "value": row.id,
         "tot_distance": row.compute_total_distance(),
         "tot_secs": row.compute_total_seconds(),
         "is_arm_aux_allowed": row.is_arm_aux_allowed(),
         "is_kick_aux_allowed": row.is_kick_aux_allowed(),
         "is_body_aux_allowed": row.is_body_aux_allowed(),
         "is_breath_aux_allowed": row.is_breath_aux_allowed()
        }, {
         ...
        }]


## Team attended Meetings [/teams/count_meetings{id}]
### Get a Team's total number of attended meetings [GET]
Computes and returns the total number of meetings in which a Team has at least an individual result.
Returns 0 in case of error or when no results are found.

+ Parameters
    - id
        The team_id

+ Response 200 (application/json)

        {10}


## Team total Results [/teams/count_results{id}]
### Get a Team's total number of attended meetings [GET]
Computes and returns the total number of individual and relay results found for a specified Team.
Returns 0 in case of error or when no results are found.

+ Parameters
    - id
        The team_id

+ Response 200 (application/json)

        {10}


## Team computed details [/teams/count_details{id}]
### Get both Team's total number of attended meetings and its total number of results [GET]
Combines both methods above to return a localized & composed string rendered as JSON text.
Returns an empty text in case of error.

+ Parameters
    - id
        The team_id

+ Response 200 (application/json)

        {"Total attended meetings: 256, Total results: 2478"}
