#!/bin/bash
# --- Hand-picked pages for which the cache must be rebuilt: ---
echo "- Goggle Cup:"
curl -# http://master-goggles.org/it/teams/goggle_cup/1 > /dev/null

echo "- Most searched Teams' radio:"
curl -# http://master-goggles.org/it/teams/radio/233 > /dev/null

echo "- Most searched Swimmers' radio:"
curl -# http://master-goggles.org/it/swimmers/radio/92 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/49 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/14 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/137 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/966 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/961 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/951 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/785 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/580 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/579 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4855 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4853 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4852 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4850 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/12 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/40 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1030 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1060 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1088 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1116 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1135 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1197 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1292 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1409 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1461 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1476 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1590 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1633 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1710 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1753 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1776 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/1851 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/2546 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4845 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4837 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4834 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4831 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4830 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4828 > /dev/null
curl -# http://master-goggles.org/it/swimmers/radio/4821 > /dev/null
