-- Inizio script
/*!40101 SET character_set_client = latin1 */;
/*!40103 SET TIME_ZONE='+00:00' */;

SET AUTOCOMMIT=0;
START TRANSACTION;

--
-- Aggiunta dati Mondiali FINA 2014 per la tabella team_affiliations
-- 
INSERT INTO team_affiliations (id,season_id,team_id,name,number,must_calculate_goggle_cup,user_id,lock_version,created_at,updated_at) VALUES 
(502,134,1,'CSI NUOTO OBER FERRARI','?',1,2,0,CURDATE(),CURDATE());

--
-- Aggiunta dati  Mondiali FINA 2014 per la tabella badges
-- 
INSERT INTO badges (id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(8419,134,1,1025,'?',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 134),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 134),0,CURDATE(),CURDATE());

--
-- Aggiunta dati Mondiali FINA 2014 per la tabella meetings
-- 
INSERT INTO meetings (id,header_date,season_id,entry_deadline,has_warm_up_pool,is_under_25_admitted,reference_phone,reference_e_mail,reference_name,notes,code,max_individual_events,max_individual_events_per_session,configuration_file,description,edition,header_year,user_id,edition_type_id,timing_type_id,individual_score_computation_type_id,relay_score_computation_type_id,meeting_score_computation_type_id,team_score_computation_type_id,lock_version,created_at,updated_at) VALUES 
(13401,'2014-08-03',134,'2014-05-31',1,0,'','','','','mondiali',5,2,'','MONDIALI MASTER',15,'2014',2,(select t.id from edition_types t where t.code = 'A'),(select t.id from timing_types t where t.code = 'A'),(select t.id from score_computation_types t where t.code = 'N'),(select t.id from score_computation_types t where t.code = 'N'),(select t.id from score_computation_types t where t.code = 'N'),(select t.id from score_computation_types t where t.code = 'N'),0,curdate(),curdate());

--
-- Aggiunta dati Mondiali FINA 2014 per la tabella meeting_sessions
-- 
INSERT INTO meeting_sessions (id,session_order,scheduled_date,meeting_id,swimming_pool_id,warm_up_time,begin_time,notes,description,user_id,day_part_type_id,lock_version,created_at,updated_at) VALUES 
(677,1,'2014-08-03',13401,152,'07:00:00','08:00:00','','FINALS',2,(select t.id from day_part_types t where t.code = ''),0,CURDATE(),CURDATE()),
(678,2,'2014-08-04',13401,152,'07:00:00','08:00:00','','FINALS',2,(select t.id from day_part_types t where t.code = ''),0,CURDATE(),CURDATE()),
(679,3,'2014-08-05',13401,152,'07:00:00','08:00:00','','FINALS',2,(select t.id from day_part_types t where t.code = ''),0,CURDATE(),CURDATE()),
(680,4,'2014-08-06',13401,152,'07:00:00','08:00:00','','FINALS',2,(select t.id from day_part_types t where t.code = ''),0,CURDATE(),CURDATE()),
(681,5,'2014-08-07',13401,152,'07:00:00','08:00:00','','FINALS',2,(select t.id from day_part_types t where t.code = ''),0,CURDATE(),CURDATE()),
(682,6,'2014-08-08',13401,152,'07:00:00','08:00:00','','FINALS',2,(select t.id from day_part_types t where t.code = ''),0,CURDATE(),CURDATE()),
(683,7,'2014-08-09',13401,152,'07:00:00','08:00:00','','FINALS',2,(select t.id from day_part_types t where t.code = ''),0,CURDATE(),CURDATE());

--
-- Aggiunta datiMondiali FINA 2014  per la tabella meeting_events
-- 
INSERT INTO meeting_events (id,event_order,begin_time,is_out_of_race,user_id,meeting_session_id,event_type_id,heat_type_id,lock_version,created_at,updated_at) VALUES 
(2414,1,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 1),(select t.id from event_types t where t.code = '800SL'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2415,1,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 2),(select t.id from event_types t where t.code = '200DO'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2416,2,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 2),(select t.id from event_types t where t.code = '100SL'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2417,3,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 2),(select t.id from event_types t where t.code = '100RA'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2418,1,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 3),(select t.id from event_types t where t.code = '400MI'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2419,2,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 3),(select t.id from event_types t where t.code = '200SL'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2420,3,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 3),(select t.id from event_types t where t.code = '50FA'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2421,1,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 4),(select t.id from event_types t where t.code = '50SL'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2422,2,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 4),(select t.id from event_types t where t.code = '200MI'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2423,3,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 4),(select t.id from event_types t where t.code = '100FA'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2424,4,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 4),(select t.id from event_types t where t.code = '50DO'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2425,1,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 6),(select t.id from event_types t where t.code = '200RA'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2426,2,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 6),(select t.id from event_types t where t.code = '100DO'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2427,3,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 6),(select t.id from event_types t where t.code = '200FA'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2428,1,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 7),(select t.id from event_types t where t.code = '50DO'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE()),
(2429,2,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 13401 and t.session_order = 7),(select t.id from event_types t where t.code = '400SL'),(select t.id from heat_types t where t.code = 'F'),0,CURDATE(),CURDATE());

--
-- Aggiunta dati Mondiali FINA 2014 per la tabella meeting_programs
-- 
INSERT INTO meeting_programs (id,event_order,user_id,meeting_event_id,gender_type_id,category_type_id,pool_type_id,lock_version,created_at,updated_at) VALUES 
(7066,1,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 13401 and et.code = '400MI'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 134),(select t.id from pool_types t where t.code = '50'),0,CURDATE(),CURDATE()),
(7067,2,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 13401 and et.code = '200FA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 134),(select t.id from pool_types t where t.code = '50'),0,CURDATE(),CURDATE()),
(7068,3,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 13401 and et.code = '200MI'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 134),(select t.id from pool_types t where t.code = '50'),0,CURDATE(),CURDATE()),
(7069,4,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 13401 and et.code = '100FA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 134),(select t.id from pool_types t where t.code = '50'),0,CURDATE(),CURDATE());

--
-- Aggiunta dati Mondiali FINA 2014 per la tabella meeting_individual_results
-- 
INSERT INTO meeting_individual_results (id,rank,standard_points,minutes,seconds,hundreds,team_points,swimmer_id,team_id,user_id,is_disqualified,is_out_of_race,goggle_cup_points,reaction_time,meeting_program_id,badge_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(110964,18,'0',5,24,49,'0',1025,1,2,0,0,1013.78,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '400MI' and ms.meeting_id = 13401 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1025 and b.team_id = 1 and m.id = 13401),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 13401),0,CURDATE(),CURDATE()),
(110965,16,'0',2,31,64,'1',1025,1,2,0,0,998.88,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200FA' and ms.meeting_id = 13401 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1025 and b.team_id = 1 and m.id = 13401),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 13401),0,CURDATE(),CURDATE()),
(110966,30,'0',2,30,98,'2',1025,1,2,0,0,1021.39,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200MI' and ms.meeting_id = 13401 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1025 and b.team_id = 1 and m.id = 13401),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 13401),0,CURDATE(),CURDATE()),
(110967,31,'0',1,6,2,'3',1025,1,2,0,0,995.3,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100FA' and ms.meeting_id = 13401 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1025 and b.team_id = 1 and m.id = 13401),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 13401),0,CURDATE(),CURDATE());

--
-- Aggiunta passaggi per gare Mondiali FINA 2014 passages
-- 
delete from passages where id between 2731 and 2748;
INSERT INTO passages (id,minutes,seconds,hundreds,swimmer_id,user_id,team_id,passage_type_id,meeting_program_id,meeting_individual_result_id,lock_version,created_at,updated_at) VALUES 
(2731,0,31,92,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '50'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '400MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '400MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2732,0,36,7,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '100'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '400MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '400MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2733,0,43,48,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '150'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '400MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '400MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2734,0,44,27,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '200'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '400MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '400MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2735,0,46,28,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '250'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '400MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '400MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2736,0,47,43,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '300'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '400MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '400MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2737,0,37,10,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '350'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '400MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '400MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2738,0,37,94,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '400'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '400MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '400MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2739,0,30,17,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '50'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '200MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '200MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2740,0,39,99,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '100'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '200MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '200MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2741,0,45,46,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '150'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '200MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '200MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2742,0,35,36,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '200'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '200MI' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '200MI' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2743,0,30,86,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '50'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '100FA' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '100FA' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2744,0,35,16,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '100'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '100FA' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '100FA' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2745,0,32,25,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '50'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '200FA' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '200FA' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2746,0,38,49,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '100'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '200FA' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '200FA' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2747,0,40,8,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '150'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '200FA' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '200FA' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE()),
(2748,0,40,82,1025,2,1,(select t.id from passage_types t where t.length_in_meters = '200'),(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code =  '200FA' and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),(select mir.id from meeting_individual_results mir join meeting_programs mp on mp.id = mir.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join meetings m on m.id = ms.meeting_id where m.id = 13401 and et.code = '200FA' and mir.swimmer_id = 1025 and mp.gender_type_id = (select s.gender_type_id from swimmers s where s.id = 1025) and mp.category_type_id = (select b.category_type_id from badges b where b.swimmer_id = 1025 and b.season_id = 134) and mp.pool_type_id = (select p.id from pool_types p where p.code = '50')),0,CURDATE(),CURDATE());

COMMIT;
-- Fine script
