/*!40101 SET character_set_client = latin1 */;
/*!40103 SET TIME_ZONE='+00:00' */;

SET AUTOCOMMIT=0;
START TRANSACTION;

--
-- Aggiunta dati Meeting 15202 per la tabella meeting_relay_swimmers
-- 
INSERT INTO meeting_relay_swimmers (relay_order,swimmer_id,minutes,seconds,hundreds,user_id,reaction_time,meeting_relay_result_id,badge_id,stroke_type_id,lock_version,created_at,updated_at) VALUES 
(1,98,0,43,9,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50MI' and ms.meeting_id = 15202 and gt.code = 'X' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 98),(select t.id from stroke_types t where t.code = 'DO'),0,CURDATE(),CURDATE()),
(2,142,0,35,47,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50MI' and ms.meeting_id = 15202 and gt.code = 'X' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 142),(select t.id from stroke_types t where t.code = 'RA'),0,CURDATE(),CURDATE()),
(3,1025,0,29,39,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50MI' and ms.meeting_id = 15202 and gt.code = 'X' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 1025),(select t.id from stroke_types t where t.code = 'FA'),0,CURDATE(),CURDATE()),
(4,138,0,37,17,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50MI' and ms.meeting_id = 15202 and gt.code = 'X' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 138),(select t.id from stroke_types t where t.code = 'SL'),0,CURDATE(),CURDATE()),
(1,98,0,40,64,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50MI' and ms.meeting_id = 15202 and gt.code = 'X' and ct.code = '100-119' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 98),(select t.id from stroke_types t where t.code = 'DO'),0,CURDATE(),CURDATE()),
(2,142,0,40,44,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50MI' and ms.meeting_id = 15202 and gt.code = 'X' and ct.code = '100-119' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 142),(select t.id from stroke_types t where t.code = 'RA'),0,CURDATE(),CURDATE()),
(3,1025,0,38,78,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50MI' and ms.meeting_id = 15202 and gt.code = 'X' and ct.code = '100-119' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 1025),(select t.id from stroke_types t where t.code = 'FA'),0,CURDATE(),CURDATE()),
(4,138,0,38,41,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'M4X50MI' and ms.meeting_id = 15202 and gt.code = 'X' and ct.code = '100-119' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 138),(select t.id from stroke_types t where t.code = 'SL'),0,CURDATE(),CURDATE()),
(1,1016,0,49,62,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15202 and gt.code = 'M' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 1016),(select t.id from stroke_types t where t.code = 'DO'),0,CURDATE(),CURDATE()),
(2,142,0,36,7,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15202 and gt.code = 'M' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 142),(select t.id from stroke_types t where t.code = 'RA'),0,CURDATE(),CURDATE()),
(3,1025,0,29,48,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15202 and gt.code = 'M' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 1025),(select t.id from stroke_types t where t.code = 'FA'),0,CURDATE(),CURDATE()),
(4,1227,0,28,87,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15202 and gt.code = 'M' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari'),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15202) and b.swimmer_id = 1227),(select t.id from stroke_types t where t.code = 'SL'),0,CURDATE(),CURDATE());

commit;