-- Leega
-- 07/03/2016
-- 15104 csiprova4 50Special (100MI)

--
-- Aggiunta dati FIN 15/16 per la tabella meeting_events
-- 
INSERT INTO meeting_events (event_order,begin_time,is_out_of_race,user_id,meeting_session_id,event_type_id,heat_type_id,lock_version,created_at,updated_at) VALUES 
(6,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 15104 and t.session_order = 1),(select t.id from event_types t where t.code = '100MI'),(select t.id from heat_types t where t.code = 'P'),0,CURDATE(),CURDATE());

--
-- Aggiunta dati FIN 15/16 per la tabella meeting_programs
-- 
INSERT INTO meeting_programs (event_order,user_id,meeting_event_id,gender_type_id,category_type_id,pool_type_id,time_standard_id,lock_version,created_at,updated_at) VALUES 
(6,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = '100MI'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '50S' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),(select ts.id from time_standards ts where ts.season_id = 151 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'F') and ts.event_type_id = (select t.id from event_types t where t.code = '100MI') and ts.category_type_id = (select t.id from category_types t where t.code = '50S' and t.season_id = 151) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE()),
(6,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = '100MI'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '50S' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),(select ts.id from time_standards ts where ts.season_id = 151 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'M') and ts.event_type_id = (select t.id from event_types t where t.code = '100MI') and ts.category_type_id = (select t.id from category_types t where t.code = '50S' and t.season_id = 151) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE());

--
-- Aggiunta dati FIN 15/16 per la tabella meeting_individual_results
-- 
INSERT INTO meeting_individual_results (rank,standard_points,minutes,seconds,hundreds,team_points,swimmer_id,team_id,user_id,is_disqualified,is_out_of_race,goggle_cup_points,reaction_time,meeting_program_id,badge_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(1,'0',1,15,80,'24',20993,10,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 20993 and b.team_id = 10 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15104),0,CURDATE(),CURDATE()),
(2,'0',1,16,20,'21',1449,9,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1449 and b.team_id = 9 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15104),0,CURDATE(),CURDATE()),
(3,'0',1,16,60,'18',1841,1,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1841 and b.team_id = 1 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15104),0,CURDATE(),CURDATE()),
(4,'0',1,20,0,'15',11733,17,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 11733 and b.team_id = 17 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(4,'0',1,20,0,'15',1522,5,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1522 and b.team_id = 5 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(6,'0',1,28,30,'9',1476,18,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1476 and b.team_id = 18 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE()),
(1,'0',1,5,0,'24',1824,21,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1824 and b.team_id = 21 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 21 and m.id = 15104),0,CURDATE(),CURDATE()),
(2,'0',1,6,30,'21',1102,17,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1102 and b.team_id = 17 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(3,'0',1,7,10,'18',1164,5,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1164 and b.team_id = 5 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(4,'0',1,8,20,'15',1845,18,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1845 and b.team_id = 18 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE()),
(5,'0',1,9,80,'12',1308,32,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1308 and b.team_id = 32 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 32 and m.id = 15104),0,CURDATE(),CURDATE()),
(6,'0',1,12,70,'9',25,4,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 25 and b.team_id = 4 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 4 and m.id = 15104),0,CURDATE(),CURDATE()),
(7,'0',1,16,0,'6',4849,9,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 4849 and b.team_id = 9 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15104),0,CURDATE(),CURDATE()),
(8,'0',1,18,50,'3',1409,35,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1409 and b.team_id = 35 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 35 and m.id = 15104),0,CURDATE(),CURDATE());
