-- Leega
-- 23/03/2016
-- Fix for id differencies between devel and prod fo 15104 csiprova4 50Special and relays

-- Removing previous data
delete from meeting_individual_results where meeting_program_id between 42267 and 42268;
delete from meeting_programs where id between 42267 and 42268;
delete from meeting_relay_results where meeting_program_id between 42269 and 42274;
delete from meeting_programs where id between 42269 and 42274;


-- 50Special
--
-- Aggiunta dati 50Special per la tabella meeting_programs
--
INSERT INTO meeting_programs (id,event_order,user_id,meeting_event_id,gender_type_id,category_type_id,pool_type_id,time_standard_id,lock_version,created_at,updated_at) VALUES 
(42024,6,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = '100MI'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '50S' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),(select ts.id from time_standards ts where ts.season_id = 151 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'F') and ts.event_type_id = (select t.id from event_types t where t.code = '100MI') and ts.category_type_id = (select t.id from category_types t where t.code = '50S' and t.season_id = 151) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE()),
(42025,6,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = '100MI'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '50S' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),(select ts.id from time_standards ts where ts.season_id = 151 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'M') and ts.event_type_id = (select t.id from event_types t where t.code = '100MI') and ts.category_type_id = (select t.id from category_types t where t.code = '50S' and t.season_id = 151) and ts.pool_type_id = (select t.id from pool_types t where t.code = '25')),0,CURDATE(),CURDATE());

--
-- Aggiunta dati 50Special per la tabella meeting_individual_results
--
INSERT INTO meeting_individual_results (id,rank,standard_points,minutes,seconds,hundreds,team_points,swimmer_id,team_id,user_id,is_disqualified,is_out_of_race,goggle_cup_points,reaction_time,meeting_program_id,badge_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(285611,1,'0',1,15,80,'24',20993,10,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 20993 and b.team_id = 10 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15104),0,CURDATE(),CURDATE()),
(285612,2,'0',1,16,20,'21',1449,9,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1449 and b.team_id = 9 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15104),0,CURDATE(),CURDATE()),
(285613,3,'0',1,16,60,'18',1841,1,2,0,0,'993.47',0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1841 and b.team_id = 1 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15104),0,CURDATE(),CURDATE()),
(285614,4,'0',1,20,0,'15',11733,17,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 11733 and b.team_id = 17 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(285615,4,'0',1,20,0,'15',1522,5,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1522 and b.team_id = 5 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(285616,6,'0',1,28,30,'9',1476,18,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1476 and b.team_id = 18 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE()),
(285617,1,'0',1,5,0,'24',1824,21,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1824 and b.team_id = 21 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 21 and m.id = 15104),0,CURDATE(),CURDATE()),
(285618,2,'0',1,6,30,'21',1102,17,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1102 and b.team_id = 17 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(285619,3,'0',1,7,10,'18',1164,5,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1164 and b.team_id = 5 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(285620,4,'0',1,8,20,'15',1845,18,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1845 and b.team_id = 18 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE()),
(285621,5,'0',1,9,80,'12',1308,32,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1308 and b.team_id = 32 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 32 and m.id = 15104),0,CURDATE(),CURDATE()),
(285622,6,'0',1,12,70,'9',25,4,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 25 and b.team_id = 4 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 4 and m.id = 15104),0,CURDATE(),CURDATE()),
(285623,7,'0',1,16,0,'6',4849,9,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 4849 and b.team_id = 9 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15104),0,CURDATE(),CURDATE()),
(285624,8,'0',1,18,50,'3',1409,35,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100MI' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1409 and b.team_id = 35 and m.id = 15104),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 35 and m.id = 15104),0,CURDATE(),CURDATE());

-- Relays
--
-- Aggiunta dati per la tabella meeting_programs staffette
--
INSERT INTO meeting_programs (id,event_order,user_id,meeting_event_id,gender_type_id,category_type_id,pool_type_id,lock_version,created_at,updated_at) VALUES 
(42267,1,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = 'S8X25SL'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '001-119' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(42268,2,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = 'S8X25SL'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '120-159' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(42269,3,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = 'S8X25SL'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '160-999' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(42270,1,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = 'S8X25SL'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '001-119' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(42271,2,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = 'S8X25SL'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '120-159' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE()),
(42272,3,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15104 and et.code = 'S8X25SL'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '160-999' and t.season_id = 151),(select t.id from pool_types t where t.code = '25'),0,CURDATE(),CURDATE());

--
-- Aggiunta dei dati per la tabella meeting_relay_results
--
INSERT INTO meeting_relay_results (id,rank,meeting_points,minutes,seconds,hundreds,user_id,team_id,is_disqualified,is_out_of_race,meeting_program_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(13604,1,'24',1,56,0,2,10,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15104),0,CURDATE(),CURDATE()),
(13605,2,'21',1,57,50,2,11,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15104),0,CURDATE(),CURDATE()),
(13606,3,'18',1,58,10,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15104),0,CURDATE(),CURDATE()),
(13607,4,'15',1,58,60,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(13608,5,'12',2,1,30,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(13609,6,'0',2,4,70,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(13610,7,'6',2,5,60,2,21,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 21 and m.id = 15104),0,CURDATE(),CURDATE()),
(13611,8,'3',2,20,90,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE()),
(13612,0,'0',0,0,0,2,826,1,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 826 and m.id = 15104),0,CURDATE(),CURDATE()),
(13613,1,'24',1,34,70,2,21,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 21 and m.id = 15104),0,CURDATE(),CURDATE()),
(13614,2,'21',1,36,70,2,32,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 32 and m.id = 15104),0,CURDATE(),CURDATE()),
(13615,3,'18',1,44,30,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(13616,4,'15',1,45,0,2,10,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15104),0,CURDATE(),CURDATE()),
(13617,5,'12',1,48,0,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(13618,6,'9',1,49,90,2,9,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15104),0,CURDATE(),CURDATE()),
(13619,7,'6',1,52,0,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '001-119'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15104),0,CURDATE(),CURDATE()),
(13620,1,'24',2,7,40,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(13621,2,'21',2,10,50,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15104),0,CURDATE(),CURDATE()),
(13622,3,'18',2,15,10,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE()),
(13623,1,'24',1,43,50,2,11,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15104),0,CURDATE(),CURDATE()),
(13624,2,'21',1,45,10,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15104),0,CURDATE(),CURDATE()),
(13625,3,'18',1,50,80,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(13626,4,'15',1,52,70,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(13627,5,'0',1,55,50,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(13628,6,'9',2,7,0,2,35,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 35 and m.id = 15104),0,CURDATE(),CURDATE()),
(13629,7,'6',2,7,30,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE()),
(13630,0,'0',0,0,0,2,18,1,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '120-159'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE()),
(13631,1,'24',1,59,50,2,9,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15104),0,CURDATE(),CURDATE()),
(13632,2,'21',2,3,40,2,10,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15104),0,CURDATE(),CURDATE()),
(13633,3,'18',2,4,30,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(13634,4,'15',2,15,70,2,11,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15104),0,CURDATE(),CURDATE()),
(13635,5,'12',2,23,0,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'F' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15104),0,CURDATE(),CURDATE()),
(13636,1,'24',1,41,90,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(13637,2,'21',1,45,30,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE()),
(13638,3,'18',1,48,0,2,32,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 32 and m.id = 15104),0,CURDATE(),CURDATE()),
(13639,4,'15',1,48,20,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15104),0,CURDATE(),CURDATE()),
(13640,4,'0',1,48,20,2,5,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15104),0,CURDATE(),CURDATE()),
(13641,6,'9',1,50,90,2,9,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15104),0,CURDATE(),CURDATE()),
(13642,7,'6',1,55,0,2,11,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15104),0,CURDATE(),CURDATE()),
(13643,8,'0',1,58,20,2,9,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15104),0,CURDATE(),CURDATE()),
(13644,9,'2',1,59,0,2,4,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 4 and m.id = 15104),0,CURDATE(),CURDATE()),
(13645,10,'2',2,10,10,2,17,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15104),0,CURDATE(),CURDATE()),
(13646,11,'0',2,12,40,2,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15104),0,CURDATE(),CURDATE()),
(13647,12,'2',2,20,10,2,826,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 826 and m.id = 15104),0,CURDATE(),CURDATE()),
(13648,13,'0',2,22,0,2,18,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S8X25SL' and ms.meeting_id = 15104 and gt.code = 'M' and ct.code = '160-999'),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15104),0,CURDATE(),CURDATE());
