-- Leega
-- 03/06/2016
-- Europei Londra 2016

-- select max(id) from team_affiliations;
-- select max(id) from badges;

-- 
-- Aggiunta dati Europei LEN 2016 per la tabella seasons
-- 
INSERT INTO seasons (id,description,edition,header_year,begin_date,end_date,season_type_id,timing_type_id,edition_type_id,lock_version,created_at,updated_at) VALUES 
(153,'Campionato europeo master LEN 2016',15,'2016','2016-05-22','2016-05-29',(select t.id from season_types t where t.code = 'MASLEN'),(select t.id from timing_types t where t.code = 'A'),(select t.id from edition_types t where t.code = 'A'),0,CURDATE(),CURDATE());

--
-- Dump dei dati per la tabella category_types
-- 
INSERT INTO category_types (id,code,description,short_name,season_id,federation_code,group_name,age_begin,age_end,is_a_relay,is_out_of_race,lock_version,created_at,updated_at) VALUES 
(935,'M25','MASTER 25','M25',153,'B','MASTER',25,29,0,0,0,CURDATE(),CURDATE()),
(936,'M30','MASTER 30','M30',153,'C','MASTER',30,34,0,0,0,CURDATE(),CURDATE()),
(937,'M35','MASTER 35','M35',153,'D','MASTER',35,39,0,0,0,CURDATE(),CURDATE()),
(938,'M40','MASTER 40','M40',153,'E','MASTER',40,44,0,0,0,CURDATE(),CURDATE()),
(939,'M45','MASTER 45','M45',153,'F','MASTER',45,49,0,0,0,CURDATE(),CURDATE()),
(940,'M50','MASTER 50','M50',153,'G','MASTER',50,54,0,0,0,CURDATE(),CURDATE()),
(941,'M55','MASTER 55','M55',153,'H','MASTER',55,59,0,0,0,CURDATE(),CURDATE()),
(942,'M60','MASTER 60','M60',153,'I','MASTER',60,64,0,0,0,CURDATE(),CURDATE()),
(943,'M65','MASTER 65','M65',153,'J','MASTER',65,69,0,0,0,CURDATE(),CURDATE()),
(944,'M70','MASTER 70','M70',153,'K','MASTER',70,74,0,0,0,CURDATE(),CURDATE()),
(945,'M75','MASTER 75','M75',153,'L','MASTER',75,79,0,0,0,CURDATE(),CURDATE()),
(946,'M80','MASTER 80','M80',153,'M','MASTER',80,84,0,0,0,CURDATE(),CURDATE()),
(947,'M85','MASTER 85','M85',153,'N','MASTER',85,89,0,0,0,CURDATE(),CURDATE()),
(948,'M90','MASTER 90','M90',153,'O','MASTER',90,94,0,0,0,CURDATE(),CURDATE()),
(949,'M95','MASTER 95','M95',153,'P','MASTER',95,99,0,0,0,CURDATE(),CURDATE()),
(950,'MA0','MASTER 100','MA0',153,'Q','MASTER',100,999,0,0,0,CURDATE(),CURDATE()),
(951,'U25','UNDER 25','U25',153,'A','MASTER',16,24,0,0,0,CURDATE(),CURDATE()),
(952,'000-999','STAFF. ASSOLUTI','ASSOLUTI',153,'xX','MASTER',1,999,1,0,0,CURDATE(),CURDATE()),
(953,'100-119','STAFF. M FINO A 119','100-119',153,'xA','MASTER',100,119,1,0,0,CURDATE(),CURDATE()),
(954,'120-159','STAFF. M 120-159','120-159',153,'xB','MASTER',120,159,1,0,0,CURDATE(),CURDATE()),
(955,'160-199','STAFF. M 160-199','160-199',153,'xC','MASTER',160,199,1,0,0,CURDATE(),CURDATE()),
(956,'200-239','STAFF. M 200-239','200-239',153,'xD','MASTER',200,239,1,0,0,CURDATE(),CURDATE()),
(957,'240-279','STAFF. M 240-279','240-279',153,'xE','MASTER',240,279,1,0,0,CURDATE(),CURDATE()),
(958,'280-319','STAFF. M 280-319','280-319',153,'xF','MASTER',280,319,1,0,0,CURDATE(),CURDATE()),
(959,'320-359','STAFF. M 320-359','320-359',153,'xG','MASTER',320,359,1,0,0,CURDATE(),CURDATE()),
(960,'360-399','STAFF. M 360-399','360-399',153,'xH','MASTER',360,399,1,0,0,CURDATE(),CURDATE());

-- 
-- Aggiunta dati Europei LEN 2016 per la tabella team_affiliations
-- 
INSERT INTO team_affiliations (id,season_id,team_id,name,number,must_calculate_goggle_cup,user_id,lock_version,created_at,updated_at) VALUES 
(2421,153,1,'CSI NUOTO OBER FERRARI','?',1,2,0,CURDATE(),CURDATE());

-- 
-- Aggiunta dati Europei LEN 2016 per la tabella badges
-- 
INSERT INTO badges (id,season_id,team_id,swimmer_id,number,user_id,category_type_id,entry_time_type_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(55473,153,1,142,'?',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55474,153,1,1843,'?',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55475,153,1,11732,'?',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55476,153,1,1227,'?',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55477,153,1,23,'?',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55478,153,1,785,'?',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55479,153,1,98,'?',2,(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55480,153,1,1025,'?',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55481,153,1,1452,'?',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55482,153,1,1506,'?',2,(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE()),
(55483,153,1,1409,'?',2,(select t.id from category_types t where t.code = 'M30' and t.season_id = 153),(select t.id from entry_time_types t where t.code = ''),(select ta.id from team_affiliations ta where ta.team_id = 1 and ta.season_id = 153),0,CURDATE(),CURDATE());
-- update badges set number = '?' where id > 0 and number = '';

--
-- Goggle cup definitions
--
insert into goggle_cup_definitions (id, goggle_cup_id, season_id, lock_version, created_at, updated_at) values (25, 10, 153, 0, curdate(), curdate());

--
-- Dump dei dati per la tabella cities
-- 
insert into cities (id,name,zip,area,country,country_code,lock_version,created_at,updated_at) values 
(159,'LONDON','?','LONDON','GREAT BRITAIN','GB',0,CURDATE(),CURDATE());

--
-- Dump dei dati per la tabella swimming_pools
-- 
INSERT INTO swimming_pools (id,name,phone_number,lanes_number,address,nick_name,maps_uri,has_multiple_pools,has_open_area,has_bar,has_restaurant_service,has_gym_area,has_children_area,notes,zip,fax_number,e_mail,contact_name,user_id,city_id,pool_type_id,locker_cabinet_type_id,shower_type_id,hair_dryer_type_id,lock_version,created_at,updated_at) VALUES 
(198,'Aquatics centre','',10,'Queen Elizabeth Olympic Park','londonaquatic50','',1,0,1,1,1,1,'','','','','',2,(select t.id from cities t where t.name = 'LONDON'),(select t.id from pool_types t where t.code = '50'),(select t.id from locker_cabinet_types t where t.code = ''),(select t.id from shower_types t where t.code = ''),(select t.id from hair_dryer_types t where t.code = ''),0,CURDATE(),CURDATE());

--
-- Aggiunta dati Europei LEN 2016 per la tabella meetings
-- 
INSERT INTO meetings (id,header_date,season_id,entry_deadline,has_warm_up_pool,is_under_25_admitted,reference_phone,reference_e_mail,reference_name,notes,code,max_individual_events,max_individual_events_per_session,configuration_file,description,edition,header_year,edition_type_id,timing_type_id,individual_score_computation_type_id,relay_score_computation_type_id,meeting_score_computation_type_id,team_score_computation_type_id,is_confirmed,user_id,lock_version,created_at,updated_at) VALUES 
(15399,'2016-05-24',153,'2016-04-30',0,0,'','','','','europei',3,1,'','EUROPEI MASTER LEN',2016,'2016',(select t.id from edition_types t where t.code = 'A'),(select t.id from timing_types t where t.code = 'A'),(select t.id from score_computation_types t where t.code = 'N'),(select t.id from score_computation_types t where t.code = 'N'),(select t.id from score_computation_types t where t.code = 'N'),(select t.id from score_computation_types t where t.code = 'N'),1,2,0,curdate(),curdate());

UPDATE meetings set description = 'EUROPEI MASTER LEN', edition = header_year where id in (41, 12212);

--
-- Aggiunta dati Europei LEN 2016 per la tabella meeting_sessions
-- 
INSERT INTO meeting_sessions (id,session_order,scheduled_date,meeting_id,swimming_pool_id,warm_up_time,begin_time,notes,description,day_part_type_id,user_id,lock_version,created_at,updated_at) VALUES 
(1279,1,'2016-05-24',15399,198,'00:00:00','00:00:00','','FINALS',(select t.id from day_part_types t where t.code = 'M'),2,0,CURDATE(),CURDATE()),
(1280,2,'2016-05-25',15399,198,'00:00:00','00:00:00','','FINALS',(select t.id from day_part_types t where t.code = 'M'),2,0,CURDATE(),CURDATE()),
(1281,3,'2016-05-26',15399,198,'00:00:00','00:00:00','','FINALS',(select t.id from day_part_types t where t.code = 'M'),2,0,CURDATE(),CURDATE()),
(1282,4,'2016-05-27',15399,198,'00:00:00','00:00:00','','FINALS',(select t.id from day_part_types t where t.code = 'M'),2,0,CURDATE(),CURDATE()),
(1283,5,'2016-05-28',15399,198,'00:00:00','00:00:00','','FINALS',(select t.id from day_part_types t where t.code = 'M'),2,0,CURDATE(),CURDATE()),
(1284,6,'2016-05-29',15399,198,'00:00:00','00:00:00','','FINALS',(select t.id from day_part_types t where t.code = 'M'),2,0,CURDATE(),CURDATE());

--
-- Aggiunta dati Europei LEN 2016  per la tabella meeting_events
-- 
INSERT INTO meeting_events (id,event_order,begin_time,is_out_of_race,meeting_session_id,event_type_id,heat_type_id,user_id,lock_version,created_at,updated_at) VALUES 
(6609,1,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 1),(select t.id from event_types t where t.code = '200MI'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6610,2,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 1),(select t.id from event_types t where t.code = '800SL'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6611,3,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 2),(select t.id from event_types t where t.code = '200SL'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6612,4,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 2),(select t.id from event_types t where t.code = '50RA'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6613,5,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 2),(select t.id from event_types t where t.code = '100FA'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6614,6,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 2),(select t.id from event_types t where t.code = 'S4X50SL'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6615,7,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 3),(select t.id from event_types t where t.code = '200FA'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6616,8,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 3),(select t.id from event_types t where t.code = '50DO'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6617,9,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 3),(select t.id from event_types t where t.code = '100RA'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6618,10,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 3),(select t.id from event_types t where t.code = '400SL'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6619,11,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 3),(select t.id from event_types t where t.code = 'M4X50MI'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6620,12,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 4),(select t.id from event_types t where t.code = '200DO'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6621,13,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 4),(select t.id from event_types t where t.code = '50FA'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6622,14,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 4),(select t.id from event_types t where t.code = '100SL'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6623,16,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 5),(select t.id from event_types t where t.code = '200RA'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6624,17,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 5),(select t.id from event_types t where t.code = '50SL'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6625,18,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 5),(select t.id from event_types t where t.code = '100DO'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6626,19,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 5),(select t.id from event_types t where t.code = 'S4X50MI'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE()),
(6627,15,'00:00:00',0,(select t.id from meeting_sessions t where t.meeting_id = 15399 and t.session_order = 4),(select t.id from event_types t where t.code = 'M4X50SL'),(select t.id from heat_types t where t.code = 'F'),2,0,CURDATE(),CURDATE());

--
-- Aggiunta dati Europei LEN 2016 per la tabella meeting_programs
-- 
INSERT INTO meeting_programs (id,event_order,meeting_event_id,gender_type_id,category_type_id,pool_type_id,user_id,lock_version,created_at,updated_at) VALUES 
(73993,1,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '200MI'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(73994,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '200MI'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(73995,3,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '800SL'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(73996,4,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '200SL'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(73997,5,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '200SL'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(73998,6,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '200SL'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(73999,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '200SL'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74000,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '50RA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74001,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '50RA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74002,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '200FA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74003,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '100RA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74004,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '400SL'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74005,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '400SL'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74006,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '200DO'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74007,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '50FA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74008,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '50FA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M30' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74009,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '50FA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74010,4,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '100SL'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74011,5,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '100SL'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74012,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '50SL'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74013,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '100DO'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = 'M25' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE()),
(74014,7,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15399 and et.code = '100DO'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = 'M45' and t.season_id = 153),(select t.id from pool_types t where t.code = '50'),2,0,CURDATE(),CURDATE());

-- select * from meeting_programs where id between 73993 and 74014;
-- delete from meeting_programs where id between 73993 and 74014;
--
-- Aggiunta dati Europei LEN 2016 per la tabella meeting_individual_results
-- 
INSERT INTO meeting_individual_results (id,rank,standard_points,minutes,seconds,hundreds,team_points,swimmer_id,team_id,is_disqualified,is_out_of_race,goggle_cup_points,reaction_time,meeting_program_id,badge_id,team_affiliation_id,user_id,lock_version,created_at,updated_at) VALUES 
(436716,58,'0',2,52,4,'0',1409,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200MI' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M30'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1409 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436717,32,'0',2,30,30,'0',1025,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200MI' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1025 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436718,34,'0',11,5,35,'0',1843,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '800SL' and ms.meeting_id = 15399 and gt.code = 'F' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1843 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436719,65,'0',13,27,33,'0',11732,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '800SL' and ms.meeting_id = 15399 and gt.code = 'F' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 11732 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436720,62,'0',2,54,65,'0',98,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200SL' and ms.meeting_id = 15399 and gt.code = 'F' and ct.code = 'M45'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 98 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436721,0,'0',3,4,0,'0',11732,1,0,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200SL' and ms.meeting_id = 15399 and gt.code = 'F' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 11732 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436722,59,'0',2,32,51,'0',1843,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200SL' and ms.meeting_id = 15399 and gt.code = 'F' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1843 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436723,44,'0',2,21,86,'0',1227,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200SL' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M45'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1227 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436724,52,'0',2,14,92,'0',1025,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200SL' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1025 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436725,44,'0',0,35,27,'0',142,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50RA' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M45'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 142 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436726,85,'0',0,36,70,'0',1409,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50RA' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M30'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1409 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436727,21,'0',2,29,23,'0',1025,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200FA' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1025 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436728,42,'0',1,20,48,'0',142,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100RA' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M45'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 142 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436729,44,'0',5,20,12,'0',1227,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '400SL' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M45'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1227 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436730,33,'0',3,12,92,'0',98,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '200DO' and ms.meeting_id = 15399 and gt.code = 'F' and ct.code = 'M45'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 98 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436731,82,'0',0,31,88,'0',142,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M45'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 142 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436732,150,'0',0,33,53,'0',1409,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M30'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1409 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436733,112,'0',0,30,29,'0',1452,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1452 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436734,125,'0',0,30,6,'0',1506,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1506 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436735,118,'0',1,5,72,'0',1227,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100SL' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M45'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1227 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436736,115,'0',1,0,10,'0',1452,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100SL' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1452 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436737,198,'0',1,4,34,'0',1506,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100SL' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1506 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436738,40,'0',5,22,73,'0',1843,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '400SL' and ms.meeting_id = 15399 and gt.code = 'F' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1843 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436739,0,'0',6,32,40,'0',11732,1,0,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '400SL' and ms.meeting_id = 15399 and gt.code = 'F' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 11732 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436740,0,'0',0,0,0,'0',1506,1,0,1,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50SL' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1506 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436741,23,'0',1,11,24,'0',1452,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100DO' and ms.meeting_id = 15399 and gt.code = 'M' and ct.code = 'M25'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1452 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE()),
(436742,34,'0',1,30,51,'0',98,1,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '100DO' and ms.meeting_id = 15399 and gt.code = 'F' and ct.code = 'M45'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 98 and b.team_id = 1 and m.id = 15399),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15399),2,0,CURDATE(),CURDATE());

-- select * from meeting_individual_results where id between 436716 and 436742;
-- delete from meeting_individual_results where id between 436716 and 436742;