-- Leega
-- 23/05/2016
-- San Marino Ober Ferrari relays

--
-- Aggiunta dati staffette meeting 15214
-- 
INSERT INTO meeting_relay_swimmers (id,relay_order,swimmer_id,minutes,seconds,hundreds,user_id,reaction_time,meeting_relay_result_id,badge_id,stroke_type_id,lock_version,created_at,updated_at) VALUES 
(245,1,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'SESENA BARBARA' and b.team_id = 1 and b.season_id = 152),0,42,67,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15214 and gt.code = 'F' and ct.code = '120-159' and mrr.relay_header = 'CSI Nuoto Ober Ferrari' and mrr.rank = 3),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15214) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'SESENA BARBARA' and b.team_id = 1 and b.season_id = 152)),(select t.id from stroke_types t where t.code = 'DO'),0,CURDATE(),CURDATE()),
(246,2,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BIANCHI ELENA' and b.team_id = 1 and b.season_id = 152),0,43,92,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15214 and gt.code = 'F' and ct.code = '120-159' and mrr.relay_header = 'CSI Nuoto Ober Ferrari' and mrr.rank = 3),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15214) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BIANCHI ELENA' and b.team_id = 1 and b.season_id = 152)),(select t.id from stroke_types t where t.code = 'RA'),0,CURDATE(),CURDATE()),
(247,3,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'PEZZI STEFANIA' and b.team_id = 1 and b.season_id = 152),0,32,89,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15214 and gt.code = 'F' and ct.code = '120-159' and mrr.relay_header = 'CSI Nuoto Ober Ferrari' and mrr.rank = 3),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15214) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'PEZZI STEFANIA' and b.team_id = 1 and b.season_id = 152)),(select t.id from stroke_types t where t.code = 'FA'),0,CURDATE(),CURDATE()),
(248,4,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'CANTONI SAMANTA' and b.team_id = 1 and b.season_id = 152),0,35,46,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15214 and gt.code = 'F' and ct.code = '120-159' and mrr.relay_header = 'CSI Nuoto Ober Ferrari' and mrr.rank = 3),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15214) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'CANTONI SAMANTA' and b.team_id = 1 and b.season_id = 152)),(select t.id from stroke_types t where t.code = 'SL'),0,CURDATE(),CURDATE()),
(249,1,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'DEL RIO SIMONE' and b.team_id = 1 and b.season_id = 152),0,39,79,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15214 and gt.code = 'M' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari' and mrr.rank = 4),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15214) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'DEL RIO SIMONE' and b.team_id = 1 and b.season_id = 152)),(select t.id from stroke_types t where t.code = 'DO'),0,CURDATE(),CURDATE()),
(250,2,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'ALLORO STEFANO' and b.team_id = 1 and b.season_id = 152),0,34,95,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15214 and gt.code = 'M' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari' and mrr.rank = 4),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15214) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'ALLORO STEFANO' and b.team_id = 1 and b.season_id = 152)),(select t.id from stroke_types t where t.code = 'RA'),0,CURDATE(),CURDATE()),
(251,3,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'LIGABUE MARCO' and b.team_id = 1 and b.season_id = 152),0,32,49,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15214 and gt.code = 'M' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari' and mrr.rank = 4),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15214) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'LIGABUE MARCO' and b.team_id = 1 and b.season_id = 152)),(select t.id from stroke_types t where t.code = 'FA'),0,CURDATE(),CURDATE()),
(252,4,(select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BERTOZZI ORLANDO' and b.team_id = 1 and b.season_id = 152),0,28,78,2,0,(select mrr.id from meeting_relay_results mrr join meeting_programs mp on mp.id = mrr.meeting_program_id join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = 'S4X50MI' and ms.meeting_id = 15214 and gt.code = 'M' and ct.code = '160-199' and mrr.relay_header = 'CSI Nuoto Ober Ferrari' and mrr.rank = 4),(select b.id from badges b where b.team_id = 1 and b.season_id = (select m.season_id from meetings m where m.id = 15214) and b.swimmer_id = (select b.swimmer_id from badges b join swimmers s on s.id = b.swimmer_id where s.complete_name = 'BERTOZZI ORLANDO' and b.team_id = 1 and b.season_id = 152)),(select t.id from stroke_types t where t.code = 'SL'),0,CURDATE(),CURDATE());

