-- Leega
-- 17/04/2016
-- Import 50Secial 15105 csiprova5

/*
-- Find iut last id
select max(id) from meeting_events;
select max(id) from meeting_programs;
select max(id) from meeting_individual_results;

-- Swimmers for 50special
select distinct s.complete_name, s.id, mir.team_id
from swimmers s
	join meeting_individual_results mir on mir.swimmer_id = s.id
	join meeting_programs mp on mp.id = mir.meeting_program_id
	join meeting_events me on me.id = mp.meeting_event_id
	join meeting_sessions ms on ms.id = me.meeting_session_id
where ms.meeting_id = 15105
order by s.complete_name;
*/

--
-- Aggiunta dati 50Special per la tabella meeting_events
-- 
INSERT INTO meeting_events (id,event_order,begin_time,is_out_of_race,user_id,meeting_session_id,event_type_id,heat_type_id,lock_version,created_at,updated_at) VALUES 
(5295,6,'00:00:00',0,2,(select t.id from meeting_sessions t where t.meeting_id = 15105 and t.session_order = 1),(select t.id from event_types t where t.code = '50FA'),(select t.id from heat_types t where t.code = 'P'),0,CURDATE(),CURDATE());

--
-- Aggiunta dati 50Special per la tabella meeting_programs
-- 
INSERT INTO meeting_programs (id,event_order,user_id,meeting_event_id,gender_type_id,category_type_id,pool_type_id,time_standard_id,lock_version,created_at,updated_at) VALUES 
(50302,6,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15105 and et.code = '50FA'),(select t.id from gender_types t where t.code = 'F'),(select t.id from category_types t where t.code = '50S' and t.season_id = 151),(select t.id from pool_types t where t.code = '50'),(select ts.id from time_standards ts where ts.season_id = 151 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'F') and ts.event_type_id = (select t.id from event_types t where t.code = '50FA') and ts.category_type_id = (select t.id from category_types t where t.code = '50S' and t.season_id = 151) and ts.pool_type_id = (select t.id from pool_types t where t.code = '50')),0,CURDATE(),CURDATE()),
(50303,6,2,(select me.id from meeting_events me join meeting_sessions ms on ms.id = me.meeting_session_id join event_types et on et.id = me.event_type_id where ms.meeting_id = 15105 and et.code = '50FA'),(select t.id from gender_types t where t.code = 'M'),(select t.id from category_types t where t.code = '50S' and t.season_id = 151),(select t.id from pool_types t where t.code = '50'),(select ts.id from time_standards ts where ts.season_id = 151 and ts.gender_type_id = (select t.id from gender_types t where t.code = 'M') and ts.event_type_id = (select t.id from event_types t where t.code = '50FA') and ts.category_type_id = (select t.id from category_types t where t.code = '50S' and t.season_id = 151) and ts.pool_type_id = (select t.id from pool_types t where t.code = '50')),0,CURDATE(),CURDATE());

--
-- Aggiunta dati 50Special per la tabella meeting_individual_results
-- 
-- delete from meeting_individual_results where id between 323743 and 323757;
INSERT INTO meeting_individual_results (id,rank,standard_points,minutes,seconds,hundreds,team_points,swimmer_id,team_id,user_id,is_disqualified,is_out_of_race,goggle_cup_points,reaction_time,meeting_program_id,badge_id,team_affiliation_id,lock_version,created_at,updated_at) VALUES 
(323743,1,'0',0,31,90,'24',1491,1,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1491 and b.team_id = 1 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15105),0,CURDATE(),CURDATE()),
(323744,2,'0',0,34,0,'21',1535,17,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1535 and b.team_id = 17 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15105),0,CURDATE(),CURDATE()),
(323745,3,'0',0,34,90,'18',21044,9,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 21044 and b.team_id = 9 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15105),0,CURDATE(),CURDATE()),
(323746,4,'0',0,38,40,'15',428,10,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 428 and b.team_id = 10 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 10 and m.id = 15105),0,CURDATE(),CURDATE()),
(323747,4,'0',0,39,40,'15',4838,5,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 4838 and b.team_id = 5 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15105),0,CURDATE(),CURDATE()),
(323748,6,'0',0,42,50,'9',1807,18,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1807 and b.team_id = 18 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15105),0,CURDATE(),CURDATE()),
(323749,7,'0',0,44,0,'6',20958,4,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'F' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 20958 and b.team_id = 4 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 4 and m.id = 15105),0,CURDATE(),CURDATE()),
(323750,1,'0',0,28,10,'24',1496,1,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1496 and b.team_id = 1 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 1 and m.id = 15105),0,CURDATE(),CURDATE()),
(323751,1,'0',0,28,10,'24',803,5,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 803 and b.team_id = 5 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 5 and m.id = 15105),0,CURDATE(),CURDATE()),
(323752,3,'0',0,30,50,'18',1308,32,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1308 and b.team_id = 32 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 32 and m.id = 15105),0,CURDATE(),CURDATE()),
(323753,4,'0',0,31,0,'15',131,18,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 131 and b.team_id = 18 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 18 and m.id = 15105),0,CURDATE(),CURDATE()),
(323754,5,'0',0,31,10,'12',1506,35,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1506 and b.team_id = 35 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 35 and m.id = 15105),0,CURDATE(),CURDATE()),
(323755,6,'0',0,33,80,'9',1102,17,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 1102 and b.team_id = 17 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 17 and m.id = 15105),0,CURDATE(),CURDATE()),
(323756,6,'0',0,33,80,'9',21980,11,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 21980 and b.team_id = 11 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 11 and m.id = 15105),0,CURDATE(),CURDATE()),
(323757,8,'0',0,36,90,'3',4032,9,2,0,0,0,0,(select mp.id from meeting_programs mp join meeting_events me on me.id = mp.meeting_event_id join event_types et on et.id = me.event_type_id join meeting_sessions ms on ms.id = me.meeting_session_id join gender_types gt on gt.id = mp.gender_type_id join category_types ct on ct.id = mp.category_type_id where et.code = '50FA' and ms.meeting_id = 15105 and gt.code = 'M' and ct.code = '50S'),(select b.id from badges b join seasons s on s.id = b.season_id join meetings m on m.season_id = s.id where b.swimmer_id = 4032 and b.team_id = 9 and m.id = 15105),(select ta.id from team_affiliations ta join seasons s on s.id = ta.season_id join meetings m on m.season_id = s.id where ta.team_id = 9 and m.id = 15105),0,CURDATE(),CURDATE());
