--
-- PassagesBatchUpdater: recorded from actions by [User: leega (Marco Ligabue) ID: 2]
-- 08 June 2016 22:34:44
-- Begin script
--

INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5572, 0, 32, 76, 53377, 2, 2, '2016-06-08 20:34:45', '2016-06-08 20:34:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 32, 76, 0, 339315, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5573, 0, 39, 62, 53377, 4, 2, '2016-06-08 20:34:45', '2016-06-08 20:34:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 12, 38, 0, 339315, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5574, 0, 41, 62, 53377, 6, 2, '2016-06-08 20:34:45', '2016-06-08 20:34:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 54, 0, 0, 339315, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5575, 0, 45, 9, 53377, 8, 2, '2016-06-08 20:34:45', '2016-06-08 20:34:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 39, 9, 0, 339315, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5576, 0, 43, 0, 53392, 2, 2, '2016-06-08 20:34:45', '2016-06-08 20:34:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 43, 0, 0, 339348, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5577, 0, 50, 23, 53392, 4, 2, '2016-06-08 20:34:45', '2016-06-08 20:34:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 33, 23, 0, 339348, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5578, 0, 47, 92, 53392, 6, 2, '2016-06-08 20:34:45', '2016-06-08 20:34:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 21, 15, 0, 339348, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5579, 0, 53, 19, 53392, 8, 2, '2016-06-08 20:34:45', '2016-06-08 20:34:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, 14, 34, 0, 339348, NULL, 1409, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5580, 0, 39, 36, 53398, 2, 2, '2016-06-08 20:34:45', '2016-06-08 20:34:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 39, 36, 0, 339373, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5581, 0, 46, 26, 53398, 4, 2, '2016-06-08 20:34:46', '2016-06-08 20:34:46', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 25, 62, 0, 339373, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5582, 0, 47, 52, 53398, 6, 2, '2016-06-08 20:34:46', '2016-06-08 20:34:46', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 13, 14, 0, 339373, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5583, 0, 46, 59, 53398, 8, 2, '2016-06-08 20:34:46', '2016-06-08 20:34:46', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 59, 73, 0, 339373, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5584, 0, 39, 91, 53409, 2, 2, '2016-06-08 20:34:46', '2016-06-08 20:34:46', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 39, 91, 0, 339411, NULL, 1463, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5585, 0, 45, 16, 53409, 4, 2, '2016-06-08 20:34:46', '2016-06-08 20:34:46', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 25, 7, 0, 339411, NULL, 1463, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5586, 0, 45, 83, 53409, 6, 2, '2016-06-08 20:34:46', '2016-06-08 20:34:46', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 10, 90, 0, 339411, NULL, 1463, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5587, 0, 45, 53, 53409, 8, 2, '2016-06-08 20:34:46', '2016-06-08 20:34:46', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 56, 43, 0, 339411, NULL, 1463, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5588, 0, 40, 88, 53328, 2, 2, '2016-06-08 20:34:47', '2016-06-08 20:34:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 40, 88, 0, 339085, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5589, 0, 44, 86, 53328, 4, 2, '2016-06-08 20:34:47', '2016-06-08 20:34:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 25, 74, 0, 339085, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5590, 0, 37, 75, 53333, 2, 2, '2016-06-08 20:34:47', '2016-06-08 20:34:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 37, 75, 0, 339105, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5591, 0, 42, 97, 53333, 4, 2, '2016-06-08 20:34:47', '2016-06-08 20:34:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 20, 72, 0, 339105, NULL, 11732, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5592, 0, 31, 32, 53346, 2, 2, '2016-06-08 20:34:47', '2016-06-08 20:34:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 31, 32, 0, 339180, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5593, 0, 35, 61, 53346, 4, 2, '2016-06-08 20:34:47', '2016-06-08 20:34:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 6, 93, 0, 339180, NULL, 23, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5594, 0, 29, 90, 53342, 2, 2, '2016-06-08 20:34:47', '2016-06-08 20:34:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 29, 90, 0, 339144, NULL, 1025, 1);
INSERT INTO `passages` (`id`, `minutes`, `seconds`, `hundreds`, `meeting_program_id`, `passage_type_id`, `user_id`, `created_at`, `updated_at`, `reaction_time`, `stroke_cycles`, `not_swam_part_seconds`, `not_swam_part_hundreds`, `not_swam_kick_number`, `breath_number`, `position`, `minutes_from_start`, `seconds_from_start`, `hundreds_from_start`, `is_native_from_start`, `meeting_individual_result_id`, `meeting_entry_id`, `swimmer_id`, `team_id`)
  VALUES (5595, 0, 34, 67, 53342, 4, 2, '2016-06-08 20:34:47', '2016-06-08 20:34:47', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 4, 57, 0, 339144, NULL, 1025, 1);
