production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  database: <%= ENV['$OPENSHIFT_APP_NAME'] %>
  host: <%= ENV['$OPENSHIFT_MYSQL_DB_HOST'] %>
  port: <%= ENV['$OPENSHIFT_MYSQL_DB_PORT'] %>
  username: <%= ENV['$OPENSHIFT_MYSQL_DB_USERNAME'] %>
  password: <%= ENV['$OPENSHIFT_MYSQL_DB_PASSWORD'] %>
